#!/usr/bin/env bash

## #ddev-generated
## Description: The sqlcmd utility lets you enter Transact-SQL statements, system procedures, and script files.
## Usage: sqlcmd
## Example: ddev sqlcmd -Q "SELECT * FROM <MyTable>;"\nddev sqlcmd -d <AnotherDatabase> -Q "SELECT * FROM <MyTable>;"
## ExecRaw: true

/opt/mssql-tools18/bin/sqlcmd -C "$@"
