#ddev-generated
services:
  sqlsrv:
    container_name: ddev-${DDEV_SITENAME}-sqlsrv
    hostname: ddev-${DDEV_SITENAME}-sqlsrv

    # For available options look at https://hub.docker.com/_/microsoft-mssql-server.
    # This image that does not work with Apple M1 yet. For more details:
    # - https://github.com/microsoft/mssql-docker/issues/734
    # - https://github.com/microsoft/mssql-docker/issues/802
    image: mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04

    user: root
    volumes:
      - sqlsystem:/var/opt/mssql/
      - .:/mnt/ddev_config
    restart: "no"
    ports:
      - "${MSSQL_EXTERNAL_PORT}:1433"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:

      # With the following setting you agree with Microsoft's end user license
      # agreement.
      - ACCEPT_EULA=Y

      # The SQL Server enforces password complexity. Trying to set a password
      # that is not sufficiently complex will result in the password not be set.
      # As a result you cannot login with the "SA" user account.
      # The password for the SA account needs to follow the following policy:
      # https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16
      - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD

      # The following setting is for selecting the SQL Server edition or product
      # key. For possible options:
      # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver16
      - MSSQL_PID=$MSSQL_PID
      - MSSQL_HOST=$MSSQL_HOST
      - MSSQL_TCP_PORT=1433
      - MSSQL_DB_NAME=$MSSQL_DB_NAME

      # Sets the default collation for SQL Server. This setting is optional. The
      # current setting is best for Drupal projects. For more information, see:
      # https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver16
      - MSSQL_COLLATION=LATIN1_GENERAL_100_CI_AS_SC_UTF8

      # For more possible environment variables that can be set, see:
      # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver16

  web:
    links:
    - sqlsrv:sqlsrv

volumes:
  sqlsystem:
