name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

# Required permissions for keep-alive, used by ddev/github-action-add-on-test
permissions:
  actions: write

defaults:
  run:
    shell: bash

jobs:
  tests:
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    # We need to use the ubuntu-20.04 image because the sqlsrv service uses the
    # mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04 image.
    # See the issue https://github.com/ddev/ddev-sqlsrv/issues/29 for more
    # details.
    runs-on: ubuntu-20.04

    steps:
      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}
